//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FileServer
{
    [Serializable]
    public class GetFileStatResponse : Message
    {
        public const string k_RosMessageName = "file_server/GetFileStat";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public bool exists;
        public float modifiedTimeMs;
        public float birthtimeMs;
        public uint sizeBytes;

        public GetFileStatResponse()
        {
            this.name = "";
            this.exists = false;
            this.modifiedTimeMs = 0.0f;
            this.birthtimeMs = 0.0f;
            this.sizeBytes = 0;
        }

        public GetFileStatResponse(string name, bool exists, float modifiedTimeMs, float birthtimeMs, uint sizeBytes)
        {
            this.name = name;
            this.exists = exists;
            this.modifiedTimeMs = modifiedTimeMs;
            this.birthtimeMs = birthtimeMs;
            this.sizeBytes = sizeBytes;
        }

        public static GetFileStatResponse Deserialize(MessageDeserializer deserializer) => new GetFileStatResponse(deserializer);

        private GetFileStatResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.exists);
            deserializer.Read(out this.modifiedTimeMs);
            deserializer.Read(out this.birthtimeMs);
            deserializer.Read(out this.sizeBytes);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.exists);
            serializer.Write(this.modifiedTimeMs);
            serializer.Write(this.birthtimeMs);
            serializer.Write(this.sizeBytes);
        }

        public override string ToString()
        {
            return "GetFileStatResponse: " +
            "\nname: " + name.ToString() +
            "\nexists: " + exists.ToString() +
            "\nmodifiedTimeMs: " + modifiedTimeMs.ToString() +
            "\nbirthtimeMs: " + birthtimeMs.ToString() +
            "\nsizeBytes: " + sizeBytes.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
